[DEMO LINK]
mate-academy/react_movies-list pull request #1312
Opened 2022-12-25 18:28 UTC by batstolya

[DEMO LINK](https://batstolya.github.io/react_movies-list/)

2022-12-26 15:18 UTC, DimaKolesnyk requested changes

2022-12-26 15:18 UTC, DimaKolesnyk commented on src/components/MoviesList/MoviesList.tsx
> +  <>
CL p1.
React Fragment might be replaced with ```<div > className="movies">``` as well as make sure to remove wrapper from the ```App comp.```

2022-12-27 10:02 UTC, DimaKolesnyk approved these changes
🚀🚀🚀

2022-12-27 16:23 UTC, valerii-derkach approved these changes

2026-07-13 23:08 UTC, closed without merging