solution
mate-academy/react_movies-list pull request #1558
Opened 2023-03-13 17:15 UTC by vadym4che

[DEMO LINK](https://vadym4che.github.io/react_movies-list/)

2023-03-14 22:33 UTC, VadKol commented
![image](https://user-images.githubusercontent.com/118836537/225156975-a58273de-ccbb-46aa-81c1-c62c4e82e050.png)
why are your cards so long?

2023-03-14 22:35 UTC, VadKol commented on src/components/MovieCard/MovieCard.tsx
> +          >
add `target="_blank"`

2023-03-14 22:35 UTC, VadKol commented on src/components/MoviesList/MoviesList.tsx
> +export const MoviesList: React.FC<Props> = ({ movies = [] }) => (
```export const MoviesList: React.FC<Props> = ({ movies }) => (

2023-03-14 22:36 UTC, VadKol requested changes
Fix some bugs

2023-03-23 22:06 UTC, vadym4che commented on src/components/MovieCard/MovieCard.tsx
> +          >
done

2023-03-23 22:08 UTC, vadym4che commented on src/components/MoviesList/MoviesList.tsx
> +export const MoviesList: React.FC<Props> = ({ movies = [] }) => (
fixed

2023-03-24 09:56 UTC, sergii-nosachenko approved these changes

2023-03-24 09:56 UTC, sergii-nosachenko commented on src/components/MoviesList/MoviesList.tsx
> +      </React.Fragment>
Useless fragment

```suggestion
      <MovieCard
        movie={movie}
        key={movie.imdbId}
      />
```

2023-03-24 09:56 UTC, sergii-nosachenko commented on src/types/Movie.ts
> +  imdbId?: string;
```suggestion
  imdbId: string;
```

2024-12-09 10:33 UTC, closed without merging