solution
mate-academy/react_movies-list pull request #176
Opened 2020-10-21 10:22 UTC by andlap24

[DEMO LINK](https://andlap24.github.io/react_movies-list/)

2020-10-21 14:37 UTC, Andrii1996 approved these changes

2020-10-22 08:34 UTC, aliceblunt8 requested changes

2020-10-22 08:34 UTC, aliceblunt8 commented on src/App.js
> +      <MovieCard movies={moviesFromServer} />
you mixed up the names of the components - MovieList renders the list of MovieCards 

```suggestion
      <MovieList movies={moviesFromServer} />
```

2020-10-22 08:34 UTC, aliceblunt8 commented on src/components/MovieCard/MovieCard.js
> +      </div>
```suggestion
export const MovieList = ({ movies }) => (
  <div className="movies">
    {movies.map(movie => (
      <div className="card">
        <MovieCard {...movie} key={movie.imdbId} />
      </div>
```

2020-10-22 08:34 UTC, aliceblunt8 commented on src/components/MovieCard/MovieCard.js
> +};
use MovieCard shape here

```suggestion
MovieList.propTypes = {
  movies: PropTypes.arrayOf(MovieCard),
  ),
};
```

2020-10-22 08:34 UTC, aliceblunt8 commented on src/components/MoviesList/MoviesList.js
> +export const MoviesList = ({ title, description, imgUrl, imdbUrl }) => (
```suggestion
export const MovieCard = ({ title, description, imgUrl, imdbUrl }) => (
```

2020-10-22 08:34 UTC, aliceblunt8 commented on src/components/MoviesList/MoviesList.js
> +};
```suggestion
MovieCard.propTypes = PropTypes.shape({
  title: PropTypes.string.isRequired,
  description: PropTypes.string.isRequired,
  imgUrl: PropTypes.string.isRequired,
  imdbUrl: PropTypes.string.isRequired,
}).isRequired;
```

2020-10-22 10:07 UTC, aliceblunt8 approved these changes
good job

2020-10-22 10:07 UTC, aliceblunt8 commented on src/components/MovieCard/MovieCard.js
> +  <>
no need to use <> here

2025-12-19 13:20 UTC, closed without merging