solution
mate-academy/react_movies-list pull request #1862
Opened 2023-08-23 11:02 UTC by patryk177m

[DEMO LINK](https://patryk177m.github.io/react_movies-list/)

2023-08-23 12:33 UTC, PawelP2001 requested changes
Looks fine to me, but i think we were also supposed to move .movies and .card blocks from App.scss to MoviesList and MovieCard .scss's (i don't see any changes in those files here, maybe you forgot to commit them?)

2023-08-23 12:45 UTC, PawelP2001 approved these changes

2023-08-24 06:42 UTC, choeqq requested changes
Please make sure each component has it's own styles file

2023-08-24 06:42 UTC, choeqq commented on src/components/MoviesList/MoviesList.tsx
> +        })}
```suggestion
        {movies.map((movie: Movie) => (
            <MovieCard movie={{ ...movie }} key={movie.imdbId} />
        ))}
```

2023-08-24 06:58 UTC, patryk177m commented
[DEMO LINK](https://patryk177m.github.io/react_movies-list/)

2023-08-24 07:08 UTC, patryk177m commented
[DEMO LINK](https://github.com/mate-academy/react_movies-list/pull/1862)

2023-08-24 07:18 UTC, patryk177m commented
https://github.com/mate-academy/react_movies-list/pull/1862

2023-08-24 07:18 UTC, closed without merging