Develop
mate-academy/react_movies-list pull request #232
Opened 2021-01-13 10:42 UTC by Layrovell

[DEMO LINK](https://Layrovell.github.io/react_movies-list/)

2021-01-13 13:01 UTC, xipholena approved these changes
Класнаа робота!

2021-01-13 13:24 UTC, aliceblunt8 requested changes

2021-01-13 13:24 UTC, aliceblunt8 commented on src/components/MoviesList/MoviesList.js
> +  ));
add this to the return statement, no need to create a separate var for it

2021-01-13 13:24 UTC, aliceblunt8 commented on src/components/MoviesList/MoviesList.js
> +  ));
use spread operator to pass data
https://medium.com/@kevinyckim33/jsx-spread-operator-component-props-meaning-3c9bcadd2493

2021-01-13 13:24 UTC, aliceblunt8 commented on src/components/MoviesList/MoviesList.js
> +  ));
add key to the MovieCard itself, div is extra

2021-01-13 13:26 UTC, aliceblunt8 commented on src/components/MoviesList/MoviesList.js
> +  ));
propTypes?

2021-01-14 12:08 UTC, aliceblunt8 requested changes

2021-01-14 12:08 UTC, aliceblunt8 commented on src/components/MoviesList/MoviesList.js
> +  ));
move this to the return statement

2021-01-14 14:39 UTC, aliceblunt8 approved these changes

2024-04-30 01:16 UTC, closed without merging