solution
mate-academy/react_movies-list pull request #351
Opened 2021-05-18 14:20 UTC by Andriykooo

[DEMO LINK](https://Andriykooo.github.io/react_movies-list/)

2021-05-18 15:00 UTC, provolovskyi-illia approved these changes
Отлично, глянь одно замечание, не знаю насколько это критично

2021-05-19 09:40 UTC, aliceblunt8 requested changes

2021-05-19 09:40 UTC, aliceblunt8 commented on src/components/MoviesList/MoviesList.js
> +        <div className="card" key={movies.imdbId}>
move this div inside MovieCard component

2021-05-19 11:28 UTC, aliceblunt8 approved these changes

2022-09-21 14:45 UTC, closed without merging