Develop
mate-academy/react_movies-list pull request #366
Opened 2021-05-19 11:23 UTC by ivan-shpynda

[DEMO LINK](https://ivan-shpynda.github.io/react_movies-list/)

2021-05-19 13:16 UTC, illisogori approved these changes
Отлично.

2021-05-19 13:16 UTC, illisogori commented on src/components/MoviesList/MoviesList.js
> +import { MovieCard } from '../MovieCard';
```suggestion
import { MovieCard } from '../MovieCard';
```
данные лучше получать в App.js и передавать в компоненты.

2021-05-19 13:17 UTC, illisogori approved these changes

2021-05-19 13:17 UTC, illisogori commented on src/components/MoviesList/MoviesList.js
>  import './MoviesList.scss';
данные лучше получать в App.js и передавать в компоненты.

2021-05-19 14:54 UTC, VinnieJ-2k20 requested changes
Some minor fixes left.
Don't forget to validate data types for fields that you use.

2021-05-19 14:54 UTC, VinnieJ-2k20 commented on src/components/MoviesList/MoviesList.js
>  );
Need validation for `movie.imdbId` using `propTypes`

2021-05-20 06:24 UTC, VinnieJ-2k20 requested changes
One more fix needed.

Lists in React must always have correct keys.

2021-05-20 06:24 UTC, VinnieJ-2k20 commented on src/components/MoviesList/MoviesList.js
> +    imdbId: PropTypes.string,
`imdbId` must be required.

2021-05-20 14:33 UTC, VinnieJ-2k20 approved these changes

2024-09-13 09:51 UTC, closed without merging