Solution
mate-academy/react_movies-list pull request #379
Opened 2021-05-19 16:40 UTC by BilliZane

[DEMO LINK](https://billizane.github.io/react_movies-list/)

2021-05-19 16:45 UTC, Bogdan-Kotsupey approved these changes
good job!

2021-05-20 06:26 UTC, VinnieJ-2k20 requested changes
One more fix needed.

Lists in React must always have correct keys.

2021-05-20 06:26 UTC, VinnieJ-2k20 commented on src/components/MoviesList/MoviesList.js
> +    imdbId: PropTypes.string,
`imdbId` must be required

2021-05-20 07:04 UTC, VinnieJ-2k20 approved these changes

2023-09-26 15:11 UTC, closed without merging