Split into components
mate-academy/react_movies-list pull request #434
Opened 2021-07-19 11:19 UTC by andrii-balitskyi

[DEMO LINK](https://andrii-balitskyi.github.io/react_movies-list/)

2021-07-19 18:54 UTC, mihay0113 commented on src/components/MovieCard/MovieCard.js
> +          // eslint-disable-next-line max-len
Комментарии нужно убирать

2021-07-19 18:56 UTC, mihay0113 approved these changes

2021-07-20 07:21 UTC, solaryasha requested changes

2021-07-20 07:21 UTC, solaryasha commented on src/App.js
> +      <MoviesList {...moviesFromServer} />
Явно вказуй, які пропси передаєш. Переписувати об'єкт props непотрібно

2021-07-20 07:21 UTC, solaryasha commented on src/components/MovieCard/MovieCard.js
> +          // eslint-disable-next-line max-len
Погоджуюся, прибери цей коментар

2021-07-20 07:21 UTC, solaryasha commented on src/components/MoviesList/MoviesList.js
> +    {moviesFromServer.map(movie => <MovieCard {...movie} key={imdbId} />)}
```suggestion
    {
      moviesFromServer.map(
        movie => <MovieCard {...movie} key={imdbId} />
      )
    }
```

2021-07-20 07:21 UTC, solaryasha commented on src/components/MoviesList/MoviesList.js
> +    {moviesFromServer.map(movie => <MovieCard {...movie} key={imdbId} />)}
Вказуй явно які пропси передаєш

2021-07-20 11:22 UTC, solaryasha approved these changes

2021-07-20 11:22 UTC, solaryasha commented on src/components/MoviesList/MoviesList.js
> +    {movies.map(movie => <MovieCard movie={movie} key={movie.imdbId} />)}
```suggestion
    {
      movies.map(
        movie => <MovieCard movie={movie} key={movie.imdbId} />
      )
    }
```

2021-07-20 11:22 UTC, solaryasha commented on src/components/MoviesList/MoviesList.js
> +      imdbId: PropTypes.string.isRequired,
Потрібно ще описати пропсу movie

2024-04-05 13:09 UTC, closed without merging