Solution???
mate-academy/react_movies-list pull request #435
Opened 2021-07-19 12:56 UTC by Vivdyuk

[DEMO LINK](https://vivdyuk.github.io/react_movies-list/)

2021-07-19 13:00 UTC, NYaremchuk approved these changes

2021-07-19 14:12 UTC, ArtemTopolskyi requested changes

2021-07-19 14:12 UTC, ArtemTopolskyi commented on src/components/MoviesList/MoviesList.js
> +  ))
Тебе не нужно импортировать moviesFromServer, ты же передаешь массив фильмов, как пропс.

2021-07-19 14:12 UTC, ArtemTopolskyi commented on src/components/MoviesList/MoviesList.js
> +    <MovieCard {...movie} />
```suggestion
export const MoviesList = ({ movies }) => (
  movies.map(movie => (
    <MovieCard {...movie} />
```

2021-07-19 14:12 UTC, ArtemTopolskyi commented on src/App.js
> +        <MoviesList {...moviesFromServer} />
зачем здесь спред оператор?

2021-07-20 07:42 UTC, ArtemTopolskyi requested changes

2021-07-20 07:42 UTC, ArtemTopolskyi commented on src/components/MovieCard/MovieCard.js
> +            // eslint-disable-next-line max-len
?

2021-07-20 07:42 UTC, ArtemTopolskyi commented on src/components/MoviesList/MoviesList.js
> +    <MovieCard {...movie} />
лучше явно передавать объект, без spread оператора

2021-07-20 07:42 UTC, ArtemTopolskyi commented on src/components/MoviesList/MoviesList.js
> +  ))
нет описания типов

2021-07-20 14:05 UTC, ArtemTopolskyi approved these changes

2023-02-13 12:06 UTC, closed without merging