solution
mate-academy/react_movies-list pull request #471
Opened 2021-08-31 21:10 UTC by Vova-Stoliar

[DEMO LINK](https://<Vova-Stoliar>.github.io/react_movies-list/)

2021-09-01 11:53 UTC, george-w-boo approved these changes
В принципі все норм, за виключенням того, що demo-link не працює та не виконана 4-та умова задачі: All the fields in the movie except the description are required

2021-09-01 12:00 UTC, varseniuk requested changes

2021-09-01 12:00 UTC, varseniuk commented on src/components/MoviesList/MoviesList.tsx
> +}
```suggestion
interface Film {
  [key: string]: string;
}
```
Let's describe all fields of this object (title. description, imdbId etc.) and move this interface to a separate file (like `src/types/Film.tsx`)

2021-09-01 12:00 UTC, varseniuk commented on src/components/MovieCard/MovieCard.tsx
> +};
```suggestion
type Props = {
  film: Film;
};
```
You should describe props here

2021-09-01 12:00 UTC, varseniuk commented on src/components/MovieCard/MovieCard.tsx
> +  } = film;
```suggestion
export const MovieCard: React.FC<Props> = (props) => {
  const {
    title, description, imgUrl, imdbUrl,
  } = props;
```

2021-09-01 12:00 UTC, varseniuk commented on src/components/MoviesList/MoviesList.tsx
> +export const MoviesList: React.FC<Props> = ({ films }: Props) => (
```suggestion
  films: Film[];
};

export const MoviesList: React.FC<Props> = (props) => {
  const { films } = props;
```

2021-09-01 12:00 UTC, varseniuk commented on src/components/MoviesList/MoviesList.tsx
> +  <>
```suggestion
```
Why do you need this fragment here? This component already returns only one element - div

2021-09-03 07:36 UTC, varseniuk approved these changes
Good job!

2023-01-12 09:40 UTC, closed without merging