Solution
mate-academy/react_movies-list pull request #592
Opened 2021-12-03 12:11 UTC by dariia-romanova

[DEMO LINK](https://dariia-romanova.github.io/react_movies-list/)

2021-12-04 21:18 UTC, SerhiiKirik approved these changes
Well done 🔥

2021-12-06 13:18 UTC, illiarerun requested changes
Good job 🔥 Let's just fix one little thing:

2021-12-06 13:18 UTC, illiarerun commented on src/App.tsx
> +      />
```suggestion
      <MoviesList movies={moviesFromServer}/>
```

2021-12-06 13:18 UTC, illiarerun commented on src/components/MoviesList/MoviesList.tsx
> +}
Move that interface somewhere else and reuse it with Omit in MovieCard component

2021-12-06 13:58 UTC, illiarerun approved these changes
GJ 🔥

2023-11-19 16:06 UTC, closed without merging