solution
mate-academy/react_movies-list pull request #647
Opened 2022-01-14 12:57 UTC by andrii-koptiev

https://andrii-koptiev.github.io/react_movies-list/

2022-01-14 13:07 UTC, SavelovSerhii requested changes
Стили находятся не совсем там, где должны быть. В остальном же, вроде бы, всё нормально.

2022-01-14 13:07 UTC, SavelovSerhii commented on src/App.scss
>  }
Стили для карточек и списка находятся не в соответствующих файлах.

2022-01-14 13:20 UTC, SavelovSerhii approved these changes
Теперь всё на своих местах.

2022-01-17 15:23 UTC, Elena-brv approved these changes

2022-01-17 15:23 UTC, Elena-brv commented on src/components/MovieCard/MovieCard.tsx
> +  <>
redundant fragment

2023-09-26 21:12 UTC, closed without merging