Solution
mate-academy/react_movies-list pull request #664
Opened 2022-01-16 19:13 UTC by gnosis-frog

[DEMO LINK](https://gnosis-frog.github.io/react_movies-list/)

2022-01-18 08:36 UTC, OlegShanin reviewed
all rigth

2022-01-18 11:50 UTC, danheim requested changes

2022-01-18 11:50 UTC, danheim commented on src/App.tsx
> +      <MoviesList moviesCatalog={moviesFromServer} />
make it easer to read
```suggestion
      <MoviesList movies={moviesFromServer} />
```

2022-01-19 08:26 UTC, danheim approved these changes

2023-02-08 10:53 UTC, closed without merging