cool website about movies
mate-academy/react_movies-list pull request #688
Opened 2022-02-10 17:42 UTC by trtskvalerie

[DEMO LINK](https://trtskvalerie.github.io/react_movies-list/)

2022-02-10 18:13 UTC, tvoyammn approved these changes
нєт слов, только емоциі

2022-02-11 16:28 UTC, Anna-Tkachenko requested changes

2022-02-11 16:28 UTC, Anna-Tkachenko commented on src/components/MoviesList/MoviesList.tsx
> +  </div>
It's better to use semantic tags for list displaying
ul for list, li for each movie card

2022-02-14 12:53 UTC, OleksiiBlezniuk approved these changes
👍

2024-03-17 12:15 UTC, closed without merging