add movies list
mate-academy/react_movies-list pull request #779
Opened 2022-04-30 23:08 UTC by kkiirill

[DEMO LINK](https://kkiirill.github.io/react_movies-list/)

2022-05-01 09:06 UTC, HelenPetrovska requested changes
demo link doesn't work

2022-05-01 09:15 UTC, kkiirill commented
> demo link doesn't work

@HelenPetrovska  fixed

2022-05-01 20:06 UTC, HelenPetrovska approved these changes

2022-05-03 08:05 UTC, danylo-onishchuk approved these changes

2023-01-03 18:32 UTC, closed without merging